### ISSUE TITLE
Plugin install does not work

### ISSUE THREAD

**Issue by mushtaq** [scalastuff/esbt#1]
I get the following error:

Cannot complete the install because of a conflicting dependency.
  Software being installed: esbt 0.10.3 (esbt.feature.group 0.10.3)
  Software currently installed: Eclipse IDE for SOA Developers 1.3.0.20100617-0520 (epp.package.soa 1.3.0.20100617-0520)
  Only one of the following can be installed at once: 
    Core Resource Management 3.6.0.v20100526-0737 (org.eclipse.core.resources 3.6.0.v20100526-0737)
    Core Resource Management 3.6.1.R36x_v20110131-1630 (org.eclipse.core.resources 3.6.1.R36x_v20110131-1630)
    Core Resource Management 3.6.0.R36x_v20100825-0600 (org.eclipse.core.resources 3.6.0.R36x_v20100825-0600)
  Cannot satisfy dependency:
    From: Eclipse IDE for SOA Developers 1.3.0.20100617-0520 (epp.package.soa 1.3.0.20100617-0520)
    To: org.eclipse.epp.package.soa.feature.feature.group [1.3.0.20100617-0520]
  Cannot satisfy dependency:
    From: esbt 0.10.3 (esbt.feature.group 0.10.3)
    To: org.eclipse.core.resources 3.6.1
  Cannot satisfy dependency:
    From: EPP SOA Feature 1.3.0.20100617-0520 (org.eclipse.epp.package.soa.feature.feature.group 1.3.0.20100617-0520)
    To: org.eclipse.platform.feature.group [3.6.0.v20100602-9gF78GpqFt6trOGhL60z0oEx3fz-JKNwxPY]
  Cannot satisfy dependency:
    From: Eclipse Platform 3.6.0.v20100602-9gF78GpqFt6trOGhL60z0oEx3fz-JKNwxPY (org.eclipse.platform.feature.group 3.6.0.v20100602-9gF78GpqFt6trOGhL60z0oEx3fz-JKNwxPY)
    To: org.eclipse.core.resources [3.6.0.v20100526-0737]

**Comment by rditerwich** [comment]
Hi mushtaq,

Could you try again? With version 0.10.4 I've loosened the dependencies version resitrictions.

Regards,

Ruud

**Comment by mushtaq** [comment]
Same error again:

Cannot complete the install because of a conflicting dependency.
  Software being installed: esbt 0.10.4 (esbt.feature.group 0.10.4)
  Software currently installed: Eclipse IDE for SOA Developers
1.3.0.20100617-0520 (epp.package.soa 1.3.0.20100617-0520)
  Only one of the following can be installed at once:
    Core Resource Management 3.6.0.v20100526-0737
(org.eclipse.core.resources 3.6.0.v20100526-0737)
    Core Resource Management 3.6.1.R36x_v20110131-1630
(org.eclipse.core.resources 3.6.1.R36x_v20110131-1630)
    Core Resource Management 3.6.0.R36x_v20100825-0600
(org.eclipse.core.resources 3.6.0.R36x_v20100825-0600)
  Cannot satisfy dependency:
    From: Eclipse IDE for SOA Developers 1.3.0.20100617-0520
(epp.package.soa 1.3.0.20100617-0520)
    To: org.eclipse.epp.package.soa.feature.feature.group
[1.3.0.20100617-0520]
  Cannot satisfy dependency:
    From: esbt 0.10.4 (esbt.feature.group 0.10.4)
    To: org.eclipse.core.resources 3.6.1
  Cannot satisfy dependency:
    From: EPP SOA Feature 1.3.0.20100617-0520
(org.eclipse.epp.package.soa.feature.feature.group 1.3.0.20100617-0520)
    To: org.eclipse.platform.feature.group
[3.6.0.v20100602-9gF78GpqFt6trOGhL60z0oEx3fz-JKNwxPY]
  Cannot satisfy dependency:
    From: Eclipse Platform
3.6.0.v20100602-9gF78GpqFt6trOGhL60z0oEx3fz-JKNwxPY
(org.eclipse.platform.feature.group
3.6.0.v20100602-9gF78GpqFt6trOGhL60z0oEx3fz-JKNwxPY)
    To: org.eclipse.core.resources [3.6.0.v20100526-0737]

**Comment by rditerwich** [comment]
The latest version (0.10.5) should be compatible with eclipse 3.6.0 and above...

**Comment by mushtaq** [comment]
Works now. Thanks.
