### ISSUE TITLE
Update not working on SNAPSHOTs

### ISSUE THREAD

**Issue by pdale** [scalastuff/esbt#2]
On windows at least update dependencies is not working as eclipse appears to lock the jar file.

We've been having to close eclipse, delete the jar from ivy cache, and then re-run update.

**Comment by rditerwich** [comment]
Issue fixed in version 0.10.6. Could someone please verify on windows?

**Comment by pdale** [comment]
Will it be available on the update site, or?

**Comment by rditerwich** [comment]
Fixed by 0.10.7 (available on the update site)
