### ISSUE TITLE
Using xsbt-web-plugin doesn't work

### ISSUE THREAD

**Issue by psiska** [scalastuff/esbt#3]
Simple lift project based on sbt-0.10. From console everything ok. Esbt fails to discover the myprj/project/plugins/build.sbt.

This results in following error in main build.sbt file
.metadata/sbt-plugin/tmpprj/build.sbt:9: error: not found: value webSettings
seq(webSettings: _*)
    ^
[error] Type error in expression

Checking .metadata directory shows that plugins/build.sbt is not taken in account.

**Comment by rditerwich** [comment]
Fixed by 0.10.7, see update site

**Comment by psiska** [comment]
Thanks, works like charm
