### ISSUE TITLE
[New Feature]Esbt to download sources of the dependencies

### ISSUE THREAD

**Issue by psiska** [scalastuff/esbt#4]
Esbt could be able to download source jars for dependencies when required.
ctrl + click in editor to open class in jar file, should automatically download sources and link it to jar. 

Maven integration has functionality as described.

For me this is missing to fully switch to sbt.

Thanks

**Comment by rditerwich** [comment]
Fixed in version 0.10.8, please update from update site.

Don't forget to use the sbt withSources(), like in:

libraryDependencies += "junit" % "junit" % "4.8.2" % "test" withSources()   

Best regards,

Ruud

On Sun, Jul 3, 2011 at 9:12 PM, sisken
reply@reply.github.com
wrote:
