### ISSUE TITLE
Using incorrect version of sbt

### ISSUE THREAD

**Issue by psiska** [scalastuff/esbt#5]
As I understand sbt uses internally scala 2.8.1.

I am trying to setup project in eclipse using scala 2.9.0.1 with web project support using sbt-web-plugin (https://github.com/siasia/xsbt-web-plugin).

Esbt has an issues with downloading the correct version of plugin. It insists on using the older version of sbt 0.10.0 instead of 0.10.1 and uses the 2.8.1 scala as well

sbt -web-plugin is setup as described on the page. scalaVersion is set to 2.9.0.1

Error in eclipse console is: 
 unresolved dependency: com.github.siasia#xsbt-web-plugin_2.8.1;0.1.1-0.10.0: not found

Thanks in advance.

**Comment by psiska** [comment]
I am not sure, but maybe issue is that esbt is still using 0.10.0 instead of 0.10.1.

**Comment by rditerwich** [comment]
Hi sisken,

I need to upgrade esbt to sbt 0.10.1. Unfortunately, i'm going on
holiday tomorrow. I'll look at it over 2 weeks.

Gr,
Ruud

On Tue, Aug 2, 2011 at 11:09 PM, sisken
reply@reply.github.com
wrote:

**Comment by psiska** [comment]
Ok Thanks :)

**Comment by rditerwich** [comment]
I don't know about the web plugging, but esbt 0.10.9 works with sbt 0.10.1
