### ISSUE TITLE
Should work with project/*.scala

### ISSUE THREAD

**Issue by nafg** [scalastuff/esbt#6]
Currently it seems esbt is only activated for projects with a build.sbt file. It would be good if it worked also for projects using full configuration.
Also, currently if I make an empty build.sbt file, will esbt still get the correct dependencies from project/Build.scala?

Thanks.

**Comment by rditerwich** [comment]
esbt 0.10.9 works for full configurations, even without build.sbt

**Comment by nafg** [comment]
When is it available?
